name: unrouter_example
description: Pure Dart example for unrouter core.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  unrouter:
    path: ..

dependency_overrides:
  unrouter_machine:
    path: ../../unrouter_machine
