name: unrouter
description: "A declarative Flutter router that feels like the browserâ€™s history & SwiftUIâ€™s NavigationStack philosophy."
version: 0.1.0

repository: https://github.com/medz/unrouter

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  routingkit: ^5.1.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
