name: unrouter
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  ht: ^0.2.0
  oref: ^2.8.0
  roux: ^0.2.0
  unstory: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
