name: unrouter
description: "Minimal router built on zenrouter with Route/RouterView/useRouter APIs."
version: 0.0.1

repository: https://github.com/medz/unrouter

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  zenrouter:
    path: zenrouter/packages/zenrouter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
