name: unrouter
description: "A fresh redesign of Unrouter."
version: 0.0.1
repository: https://github.com/medz/unrouter

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  roux: ^0.1.1
  unstory: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
