name: unrouter
description: "A Flutter router that gives you routing flexibility: define routes centrally, scope them to widgets, or mix both - with browser-style history navigation."
version: 0.6.0

repository: https://github.com/medz/unrouter
funding:
  - https://github.com/sponsors/medz
topics:
  - router
  - routing
  - navigation

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^10.0.1
  coal: ^0.0.5
  meta: ^1.17.0
  path: ^1.9.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

executables:
  unrouter: unrouter
