name: unrouter
description: "A platform-agnostic URL-first typed router for Dart."
version: 0.10.0
repository: https://github.com/medz/unrouter
topics:
  - dart
  - router
  - navigation
  - routing
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  roux: ^0.1.1
  unstory: ^0.1.1
  unrouter_machine: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
