name: unrouter_machine
description: State machine kernel for unrouter ecosystem.
version: 0.1.0
repository: https://github.com/medz/unrouter
resolution: workspace

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
