name: jaspr_unrouter
description: Jaspr adapter package for unrouter.
version: 0.1.0
repository: https://github.com/medz/unrouter
topics:
  - jaspr
  - router
  - navigation
  - routing
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  jaspr: ^0.22.2
  unrouter: ^0.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
