name: flutter_unrouter_example
description: Example app for flutter_unrouter adapter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_unrouter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  unrouter_machine:
    path: ../../unrouter_machine
  unrouter:
    path: ../../unrouter

flutter:
  uses-material-design: true
