name: nocterm_unrouter
description: Nocterm adapter package for unrouter.
version: 0.1.0
repository: https://github.com/medz/unrouter
topics:
  - nocterm
  - router
  - navigation
  - routing
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  nocterm: ^0.5.0
  unstory: ^0.1.1
  unrouter: ^0.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
